openapi: 3.1.0
info:
  version: 1.0.0
  title: TTMI Dubai
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
tags:
  - name: Authentication
    description: Login with account from global app
  - name: Vehicle
    description: API for get vehicle data
  - name: Parking
    description: API for parking service
  - name: Fuel Delivery
    description: API for Fuel service
paths:
  /authentication: 
    $ref: paths/authentication.yaml
  /vehicles: 
    $ref: paths/vehicle.yaml
  /vehicles/{id}: 
    $ref: paths/vehicle_detail.yaml
  /parkings/zone/nearest: 
    $ref: paths/zone_nearest.yaml
  /parkings/zone/order: 
    $ref: paths/parking_order.yaml
  /parkings/zone/order/{id}: 
    $ref: paths/parking_order_id.yaml
  /parkings/zone/orders: 
    $ref: paths/parking_orders.yaml
  /parkings/fuel_delivery/booking_slot: 
    $ref: paths/fuel_delivery_booking_slot.yaml
  /parkings/fuel_delivery/services: 
    $ref: paths/fuel_delivery_services.yaml
  /parkings/fuel_delivery: 
    $ref: paths/fuel_delivery.yaml
  /parkings/fuel_delivery/{id}: 
    $ref: paths/fuel_delivery_id.yaml
  /parkings/fuel_delivery/{id}/cancel: 
    $ref: paths/fuel_delivery_id_cancel.yaml
# components:
#   securitySchemes:y
#     main_auth:
#       type: oauth2
#       flows:
#         implicit:
#           authorizationUrl: http://example.com/api/oauth/dialog
#           scopes:
#             read:users: read users info
#             write:users: modify or remove users
#     api_key:
#       type: apiKey
#       in: header
#       name: api_key
#     basic_auth:
#       type: http
#       scheme: basic
